### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by francqz31** [quickvc/QuickVC-VoiceConversion#2]
Hello, I was wondering about something in the MOS scores, it does show that (QuickVC-sr) is far better than the Ground-truth itself in (N-S) evaluation , but for some reason I don't really hear it + there are noticeable Artifacts and hissing sounds, is it because all audio files have been resampled to 16k or is there some sort of leakage or a problem? If that's the case I might change sampling rate when the code is released to like 44.1khz or 22khz (if that's even possible) and retrain it on my RTX 3090 until 600k or more and see what happens. 
Also is that algorithm data hungry ? like can I train it on 2-4 hour dataset for example and have same result as the demo of the VCTK dataset that is almost 44 hours?

**Comment by quickvc** [comment]
Sorry, I am a little confused. The quickvc isn't far better than the ground truth. And where is the noticeable Artifacts and hissing sounds?

**Comment by quickvc** [comment]
The average N-MOS score of the six ground truth audio for the naturalness subjective experiment is following:

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

LJ0320032 | 312019 | 482127466000 | 4179259370002 | 260003 | 42801855180004
-- | -- | -- | -- | -- | --
4.4 | 3.7 | 4.7 | 4.15 | 4.3 | 4.075


</body>
</html>


I think the problem is P312019 in VCTK dataset: https://drive.google.com/file/d/1RLwNjmRFCvealMIrAKrX6SsWOaCEwOGk/view?usp=share_link

This is the reference voice: https://drive.google.com/file/d/1u96lxzQxjpJKp6w1xzkH2MRSt7slfXbr/view?usp=share_link
This is the converted voice: https://drive.google.com/file/d/1HJjpsMQbEADnqIWuTH2C-MRaOFzpmWs-/view?usp=share_link

In fact, the assessment of the naturalness of speech is a very subjective matter, especially when there is no significant noise in either speech.

I think the 16k sample rate does have a negative effect on the assessment of naturalness, but Hubert-soft (https://github.com/bshall/hubert) is designed for 16khz speech, so I'm not sure if Hubert-soft will negatively affect the results if higher sample rates are attempted.

I have only tested the model on the LJSpeech dataset in addition to the VCTK dataset, but LJSpeech is 16 hours of single-speaker speech data. I have no expectations that 2-4 hours of speech data will give equally good results.

Also, as mentioned in "https://github.com/MasayaKawamura/MB-iSTFT-VITS/issues/4", ms-istft-decoder does lengthen the training time considerably, so if you are not interested in model speed, perhaps the hifigan-based decoder in VITS is better suited to test your dataset.

**Comment by quickvc** [comment]
I think training Hubert-soft at a higher sampling rate is very interesting work. But from my point of view, this is a bit difficult. The original Hubert-soft is trained by LibriSpeech dataset, which is a 16KHz dataset. If you are interested, you can try to still input 16KHz voice to Hubert-soft, but the rest of the voice conversion model, such as loss design is for 24KHz.
